spring:
  application:
    name: splits

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/splitwise-db
    username: splits
    password: splits

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret:
    key: YXR0ZW1wdHNjaWVudGlzdGFkdWx0d3JpdGVyY29uc2lzdHdldGNvbnNvbmFudGxlYWQ=



#with docker
#spring:
#  config:
#    activate:
#      on-profile: docker
#  datasource:
#    url: jdbc:postgresql://db:5432/splitwise_db

